language: python
python:
  - "2.7"
#install: pip install requests==2.9.1
script: python wrapper.py -n Cell it_v1.0.6_apkpure.com.apk -appId 77bf5102757f6149cf3ca9b7254771ec -token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNyaWthbnRoIiwib3JpZ19pYXQiOjE0OTk0MTM3ODQsInVzZXJfaWQiOjE3LCJlbWFpbCI6InNyaWthbnRoLmNoaXRsYUBhY2NlbnR1cmUuY29tIiwiZXhwIjoxNTA1ODkzNzg0fQ.DnTVZSYKkKI1EkeQ710bpWqGR6mkuWbPrspkOJiBOpc
